import { Inter } from 'next/font/google'
import './globals.css'
import StoreProvider from './StoreProvider'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'POS App',
  description: 'Generated by POS app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer position="top-right" newestOnTop />
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  )
}
